### ISSUE TITLE
PCIE修复

### ISSUE THREAD

**Issue by ZR233** [dbydd/arceos_experiment#1]
枚举pcie设备时会卡死，circle os 和 linux os 都直接写死了xchi 在 bus 1 device 0 func 0，arreos 遍历出来的xchi 在 bus 0 device 1 func 0。

**Comment by dbydd** [comment]
见了鬼了，要不也学树莓派官方的linux镜像，硬编码设备地址为0x10000？
参考https://github.com/raspberrypi/linux/blob/rpi-6.1.y/drivers/reset/reset-raspberrypi.c#L51

**Comment by ZR233** [comment]
基本修复完成
