### ISSUE TITLE
jtag修复

### ISSUE THREAD

**Issue by ZR233** [dbydd/arceos_experiment#5]
jtag gdb load 失败，需要修复及编写详细文档。

**Comment by jackyliu16** [comment]
这个是一定得整个ARM-USB-TINY-H吗，搜了下都不便宜 ... 可以用Raspberry Pi Debug Probe 或者什么别的替代么？

**Comment by ZR233** [comment]
> 这个是一定得整个ARM-USB-TINY-H吗，搜了下都不便宜 ... 可以用Raspberry Pi Debug Probe 或者什么别的替代么？

能调armv8的应该都可以吧，不确定

**Comment by jackyliu16** [comment]
想问下您有现在进度的仓库可以分享吗？

**Comment by ZR233** [comment]
> 想问下您有现在进度的仓库可以分享吗？

scripts/make/raspi4.mk 里面是相关脚本

**Comment by jackyliu16** [comment]
需要注意的是，目前完成的工作对于之前的脚本（arceos原有debug）进行了修改，使之无法正常运行了
make debug

**Comment by jackyliu16** [comment]
似乎，只需要将module/axhal/build.rs中的axconfig::KERNEL_BASE_VADDR 换成 KERNEL_BASE_PADDR 就可以完成加载这个操作了

<del>但是对于后面的其他操作而言，可能还需要深入研究linker和boot之间的协作问题。 MMU 在我们的脚本中还是处于无法访问的状态。</del>

md，找到问题了 JTAG_BOOT_IMAGE 用的不是我们的镜像，而是那个实验镜像
换句话来说，我们之前gdb调试的都不是我们的代码

**Comment by dbydd** [comment]
> 想问下您有现在进度的仓库可以分享吗？

啊，这就发进组邀请
顺便，我都给的管理员权限的，拉人直接拉就行

**Comment by jackyliu16** [comment]
https://github.com/arceos-usb/arceos_experiment/pull/11

**Comment by xxczxp** [comment]
目前jtag调试是还需要同时连接串口线吗？

**Comment by dbydd** [comment]
是哦
